import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  HARNESS_ARTIFACT_CONTRACTS,
  type HarnessArtifactContract,
} from "./contracts";
import type { HarnessBundleManifest } from "./bundle";
import type { HarnessCatalog } from "../catalog";
import type { HarnessDoctorReport } from "../doctor";
import type { HarnessReport } from "../report";
import {
  DEFAULT_HARNESS_BUNDLE_REQUIRED_FILES,
} from "./contracts";
import {
  HARNESS_LANE_REGISTRY,
  isHarnessStatus,
  isRecord,
  laneHarnessCommand,
  readJsonIfPresent,
  validationCheck,
  type HarnessArtifactManifest,
  type HarnessArtifactValidationCheck,
  type HarnessArtifactValidationReport,
  type HarnessLane,
} from "../shared";

export interface HarnessArtifactValidationOptions {
  requireBundleManifest?: boolean;
  requireArtifactContracts?: boolean;
  requireReport?: boolean;
}

export function validateHarnessArtifactBundle(
  artifactRoot: string,
  generatedAt = new Date().toISOString(),
  options: HarnessArtifactValidationOptions = {},
): HarnessArtifactValidationReport {
  const checks: HarnessArtifactValidationCheck[] = [];
  const manifests = new Map<HarnessLane, HarnessArtifactManifest>();

  for (const laneDir of HARNESS_LANE_REGISTRY) {
    const manifestPath = join(artifactRoot, laneDir.artifactDir, "manifest.json");
    const manifest = readJsonIfPresent<HarnessArtifactManifest>(manifestPath);
    if (!manifest) {
      checks.push(validationCheck(
        `manifest-${laneDir.lane}`,
        laneDir.required ? "failed" : "passed",
        laneDir.required ? "required manifest is missing" : "optional manifest is missing",
        manifestPath,
        laneDir.required
          ? {
              expected: "manifest.json generated by the lane harness",
              actual: "missing",
              hint: "Run bun run harness:ci, or run the specific harness lane that owns this artifact.",
              command: laneHarnessCommand(laneDir.lane),
            }
          : {},
      ));
      continue;
    }

    const manifestErrors = validateManifestShape(manifest, laneDir.lane);
    checks.push(validationCheck(
      `manifest-${laneDir.lane}`,
      manifestErrors.length === 0 ? "passed" : "failed",
      manifestErrors.length === 0 ? "manifest schema ok" : manifestErrors.join("; "),
      manifestPath,
      manifestErrors.length === 0
        ? {}
        : {
            expected: `schemaVersion=1, lane=${laneDir.lane}, consistent status/counts/results`,
            actual: manifestErrors.join("; "),
            hint: "Re-run the lane harness and inspect its manifest writer.",
            command: laneHarnessCommand(laneDir.lane),
          },
    ));
    if (manifestErrors.length === 0) manifests.set(laneDir.lane, manifest);

    const junitPath = join(artifactRoot, laneDir.artifactDir, "junit.xml");
    checks.push(validateJUnitFile(junitPath, manifest));
  }

  checks.push(validateCatalogFile(join(artifactRoot, "harness-catalog", "catalog.json")));
  const doctor = readJsonIfPresent<HarnessDoctorReport>(join(artifactRoot, "harness-catalog", "doctor.json"));
  checks.push(validateDoctorFile(join(artifactRoot, "harness-catalog", "doctor.json"), doctor));
  checks.push(validateReportFile(
    join(artifactRoot, "harness-report", "report.json"),
    manifests,
    doctor,
    options.requireReport ?? true,
  ));
  checks.push(validateBundleManifestFile(
    join(artifactRoot, "harness-report", "bundle-manifest.json"),
    options.requireBundleManifest ?? false,
  ));
  if (options.requireArtifactContracts) {
    checks.push(...validateHarnessArtifactContracts(artifactRoot));
  }

  return {
    schemaVersion: 1,
    generatedAt,
    status: checks.some((check) => check.status === "failed") ? "failed" : "passed",
    checks,
  };
}

export function validateHarnessArtifactContracts(
  artifactRoot: string,
  contracts: readonly HarnessArtifactContract[] = HARNESS_ARTIFACT_CONTRACTS,
): HarnessArtifactValidationCheck[] {
  const root = resolve(artifactRoot);
  return contracts.map((contract) => {
    const path = join(root, contract.path);
    const value = readJsonIfPresent<Record<string, unknown>>(path);
    if (!value) {
      return validationCheck(`contract-${contract.id}`, "failed", `${contract.path} is missing or invalid JSON`, path, {
        expected: `schemaVersion=${contract.schemaVersion}, fields=${contract.fields.join(",")}`,
        actual: "missing or invalid JSON",
        hint: "Run bun run harness:ci to regenerate the full artifact bundle.",
        command: "bun run harness:ci",
      });
    }
    const errors = validateHarnessArtifactContractValue(value, contract);
    return validationCheck(
      `contract-${contract.id}`,
      errors.length === 0 ? "passed" : "failed",
      errors.length === 0 ? `${contract.path} contract ok` : errors.join("; "),
      path,
      errors.length === 0
        ? {}
        : {
            expected: `schemaVersion=${contract.schemaVersion}, top-level fields=${contract.fields.join(",")}`,
            actual: errors.join("; "),
            hint: "This artifact is a stable JSON contract. Bump schemaVersion before breaking consumers.",
            command: "bun run harness:ci",
          },
    );
  });
}

function validateManifestShape(manifest: HarnessArtifactManifest, expectedLane: HarnessLane): string[] {
  const errors: string[] = [];
  if (!isRecord(manifest)) return ["manifest is not an object"];
  if (manifest.schemaVersion !== 1) errors.push("schemaVersion must be 1");
  if (manifest.lane !== expectedLane) errors.push(`lane must be ${expectedLane}`);
  if (!isHarnessStatus(manifest.status)) errors.push("status must be passed or failed");
  if (!Number.isInteger(manifest.total) || manifest.total < 0) errors.push("total must be a non-negative integer");
  if (!Number.isInteger(manifest.passed) || manifest.passed < 0) errors.push("passed must be a non-negative integer");
  if (!Number.isInteger(manifest.failed) || manifest.failed < 0) errors.push("failed must be a non-negative integer");
  if (Number.isInteger(manifest.total) && Number.isInteger(manifest.passed) && Number.isInteger(manifest.failed)) {
    if (manifest.passed + manifest.failed !== manifest.total) errors.push("passed + failed must equal total");
    const expectedStatus = manifest.failed === 0 ? "passed" : "failed";
    if (manifest.status !== expectedStatus) errors.push(`status must be ${expectedStatus}`);
  }
  if (!Array.isArray(manifest.results)) {
    errors.push("results must be an array");
  } else {
    if (Number.isInteger(manifest.total) && manifest.results.length !== manifest.total) {
      errors.push("results length must equal total");
    }
    for (const [index, result] of manifest.results.entries()) {
      if (!isRecord(result)) {
        errors.push(`results[${index}] must be an object`);
        continue;
      }
      if (typeof result.id !== "string" || !result.id) errors.push(`results[${index}].id is required`);
      if (typeof result.name !== "string" || !result.name) errors.push(`results[${index}].name is required`);
      if (!isHarnessStatus(result.status)) errors.push(`results[${index}].status is invalid`);
    }
  }
  return errors;
}

function validateJUnitFile(path: string, manifest: HarnessArtifactManifest): HarnessArtifactValidationCheck {
  if (!existsSync(path)) return validationCheck(`junit-${manifest.lane}`, "failed", "junit.xml is missing", path, {
    expected: "junit.xml generated next to manifest.json",
    actual: "missing",
    hint: "Re-run the lane harness and inspect its JUnit writer.",
    command: laneHarnessCommand(manifest.lane),
  });
  const content = readFileSync(path, "utf8");
  const testSuite = content.match(/<testsuite\b[^>]*>/)?.[0];
  if (!testSuite) return validationCheck(`junit-${manifest.lane}`, "failed", "testsuite element is missing", path, {
    expected: "a <testsuite> element with tests and failures attributes",
    actual: "missing testsuite element",
    hint: "Inspect the generated junit.xml file.",
    command: laneHarnessCommand(manifest.lane),
  });
  const tests = Number(testSuite.match(/\btests="(\d+)"/)?.[1]);
  const failures = Number(testSuite.match(/\bfailures="(\d+)"/)?.[1]);
  const errors: string[] = [];
  if (tests !== manifest.total) errors.push(`tests must equal manifest total ${manifest.total}`);
  if (failures !== manifest.failed) errors.push(`failures must equal manifest failed ${manifest.failed}`);
  const testcaseCount = Array.from(content.matchAll(/<testcase\b/g)).length;
  if (testcaseCount !== manifest.total) errors.push(`testcase count must equal manifest total ${manifest.total}`);
  return validationCheck(
    `junit-${manifest.lane}`,
    errors.length === 0 ? "passed" : "failed",
    errors.length === 0 ? "junit schema ok" : errors.join("; "),
    path,
    errors.length === 0
      ? {}
      : {
          expected: `tests=${manifest.total}, failures=${manifest.failed}, testcase count=${manifest.total}`,
          actual: `tests=${Number.isNaN(tests) ? "missing" : tests}, failures=${Number.isNaN(failures) ? "missing" : failures}, testcase count=${testcaseCount}`,
          hint: "Compare junit.xml with the lane manifest and fix the JUnit writer.",
          command: laneHarnessCommand(manifest.lane),
        },
  );
}

function validateCatalogFile(path: string): HarnessArtifactValidationCheck {
  const catalog = readJsonIfPresent<HarnessCatalog>(path);
  if (!catalog) return validationCheck("catalog", "failed", "catalog.json is missing or invalid JSON", path, {
    expected: "valid harness catalog JSON",
    actual: "missing or invalid JSON",
    hint: "Run bun run harness:catalog.",
    command: "bun run harness:catalog",
  });
  const errors: string[] = [];
  if (catalog.schemaVersion !== 1) errors.push("schemaVersion must be 1");
  if (!Array.isArray(catalog.lanes)) errors.push("lanes must be an array");
  if (!Array.isArray(catalog.tags)) errors.push("tags must be an array");
  if (!Array.isArray(catalog.scenarios)) errors.push("scenarios must be an array");
  if (Array.isArray(catalog.lanes) && Array.isArray(catalog.scenarios)) {
    const laneScenarioCount = catalog.lanes.reduce((sum, lane) => sum + lane.scenarioCount, 0);
    if (laneScenarioCount !== catalog.scenarios.length) errors.push("lane scenario counts must equal scenarios length");
  }
  return validationCheck("catalog", errors.length === 0 ? "passed" : "failed", errors.length === 0 ? "catalog schema ok" : errors.join("; "), path, errors.length === 0 ? {} : {
    expected: "catalog lane counts, tags, and scenarios to be internally consistent",
    actual: errors.join("; "),
    hint: "Run bun run harness:catalog and inspect scenario metadata.",
    command: "bun run harness:catalog",
  });
}

function validateDoctorFile(path: string, report: HarnessDoctorReport | null): HarnessArtifactValidationCheck {
  if (!report) return validationCheck("doctor", "failed", "doctor.json is missing or invalid JSON", path, {
    expected: "valid doctor.json",
    actual: "missing or invalid JSON",
    hint: "Run bun run harness:doctor.",
    command: "bun run harness:doctor",
  });
  const errors = validateDoctorShape(report);
  return validationCheck("doctor", errors.length === 0 ? "passed" : "failed", errors.length === 0 ? "doctor schema ok" : errors.join("; "), path, errors.length === 0 ? {} : {
    expected: "doctor status to match check statuses",
    actual: errors.join("; "),
    hint: "Inspect doctor.json checks and status aggregation.",
    command: "bun run harness:doctor",
  });
}

function validateDoctorShape(report: HarnessDoctorReport): string[] {
  const errors: string[] = [];
  if (!isRecord(report)) return ["doctor report is not an object"];
  if (report.schemaVersion !== 1) errors.push("schemaVersion must be 1");
  if (!["passed", "warning", "failed"].includes(report.status)) errors.push("status is invalid");
  if (!Array.isArray(report.checks)) {
    errors.push("checks must be an array");
    return errors;
  }
  const failed = report.checks.some((check) => check.status === "failed");
  const warned = report.checks.some((check) => check.status === "warning");
  const expected = failed ? "failed" : warned ? "warning" : "passed";
  if (report.status !== expected) errors.push(`status must be ${expected}`);
  return errors;
}

function validateReportFile(
  path: string,
  manifests: ReadonlyMap<HarnessLane, HarnessArtifactManifest>,
  doctor: HarnessDoctorReport | null,
  required: boolean,
): HarnessArtifactValidationCheck {
  const report = readJsonIfPresent<HarnessReport>(path);
  if (!report) {
    return validationCheck(
      "harness-report",
      required ? "failed" : "passed",
      required ? "report.json is missing or invalid JSON" : "report.json is not present (pre-write)",
      path,
      required
        ? {
            expected: "valid aggregate harness report JSON",
            actual: "missing or invalid JSON",
            hint: "Run bun run harness:report.",
            command: "bun run harness:report",
          }
        : {},
    );
  }
  const errors: string[] = [];
  if (report.schemaVersion !== 2) errors.push("schemaVersion must be 2");
  if (!Array.isArray(report.lanes)) errors.push("lanes must be an array");
  if (!Array.isArray(report.missingRequiredLanes)) errors.push("missingRequiredLanes must be an array");
  for (const registryEntry of HARNESS_LANE_REGISTRY) {
    if (!registryEntry.required) continue;
    const lane = registryEntry.lane;
    const manifest = manifests.get(lane);
    const reportLane = report.lanes.find((item) => item.lane === lane);
    if (!manifest) {
      errors.push(`${lane} manifest missing`);
      continue;
    }
    if (!reportLane) {
      errors.push(`${lane} report lane missing`);
      continue;
    }
    if (reportLane.status !== manifest.status) errors.push(`${lane} status must match manifest`);
    if (reportLane.total !== manifest.total) errors.push(`${lane} total must match manifest`);
    if (reportLane.passed !== manifest.passed) errors.push(`${lane} passed must match manifest`);
    if (reportLane.failed !== manifest.failed) errors.push(`${lane} failed must match manifest`);
  }
  if (doctor) {
    if (!report.doctor) {
      errors.push("doctor summary is missing");
    } else {
      const doctorPassed = doctor.checks.filter((check) => check.status === "passed").length;
      const doctorWarnings = doctor.checks.filter((check) => check.status === "warning").length;
      const doctorFailed = doctor.checks.filter((check) => check.status === "failed").length;
      if (report.doctor.status !== doctor.status) errors.push("doctor status must match doctor.json");
      if (report.doctor.checks !== doctor.checks.length) errors.push("doctor checks must match doctor.json");
      if (report.doctor.passed !== doctorPassed) errors.push("doctor passed count must match doctor.json");
      if (report.doctor.warnings !== doctorWarnings) errors.push("doctor warning count must match doctor.json");
      if (report.doctor.failed !== doctorFailed) errors.push("doctor failed count must match doctor.json");
    }
  }
  errors.push(...validateReportCi(report));
  errors.push(...validateReportArtifactValidation(report));
  errors.push(...validateReportFailures(report));
  const failedLane = report.lanes.some((lane) => lane.status === "failed");
  const missingRequired = report.missingRequiredLanes.length > 0;
  const ciFailed = report.ci?.status === "failed";
  const validationFailed = report.artifactValidation?.status === "failed";
  const doctorFailed = report.doctor?.status === "failed";
  const doctorWarning = report.doctor?.status === "warning";
  const expectedStatus =
    missingRequired || failedLane || ciFailed || validationFailed || doctorFailed
      ? "failed"
      : doctorWarning
        ? "warning"
        : "passed";
  if (report.status !== expectedStatus) errors.push(`status must be ${expectedStatus}`);
  return validationCheck("harness-report", errors.length === 0 ? "passed" : "failed", errors.length === 0 ? "report schema ok" : errors.join("; "), path, errors.length === 0 ? {} : {
    expected: "aggregate report lanes and embedded ci/artifactValidation/failures to be internally consistent",
    actual: errors.join("; "),
    hint: "Open harness-report/report.json and check lane/CI/validation/failure aggregation.",
    command: "bun run harness:report",
  });
}

function validateReportCi(report: HarnessReport): string[] {
  if (!("ci" in report)) return ["ci field missing"];
  const ci = report.ci;
  if (ci === null) return [];
  const errors: string[] = [];
  if (!isRecord(ci)) return ["ci must be object or null"];
  if (!Array.isArray(ci.steps)) {
    errors.push("ci.steps must be an array");
    return errors;
  }
  const passed = ci.steps.filter((step) => step.status === "passed").length;
  const failed = ci.steps.length - passed;
  if (ci.total !== ci.steps.length) errors.push("ci.total must equal steps length");
  if (ci.passed !== passed) errors.push("ci.passed must equal passed steps");
  if (ci.failed !== failed) errors.push("ci.failed must equal failed steps");
  const expectedStatus = failed === 0 ? "passed" : "failed";
  if (ci.status !== expectedStatus) errors.push(`ci.status must be ${expectedStatus}`);
  return errors;
}

function validateReportArtifactValidation(report: HarnessReport): string[] {
  if (!("artifactValidation" in report)) return ["artifactValidation field missing"];
  const av = report.artifactValidation;
  if (av === null) return [];
  const errors: string[] = [];
  if (!isRecord(av)) return ["artifactValidation must be object or null"];
  if (!Array.isArray(av.checks)) {
    errors.push("artifactValidation.checks must be an array");
    return errors;
  }
  const passed = av.checks.filter((check) => check.status === "passed").length;
  const failed = av.checks.length - passed;
  if (av.total !== av.checks.length) errors.push("artifactValidation.total must equal checks length");
  if (av.passed !== passed) errors.push("artifactValidation.passed must equal passed checks");
  if (av.failed !== failed) errors.push("artifactValidation.failed must equal failed checks");
  const expectedStatus = failed === 0 ? "passed" : "failed";
  if (av.status !== expectedStatus) errors.push(`artifactValidation.status must be ${expectedStatus}`);
  return errors;
}

function validateReportFailures(report: HarnessReport): string[] {
  const failures = report.failures;
  if (!isRecord(failures)) return ["failures must be an object"];
  if (!Array.isArray(failures.items)) return ["failures.items must be an array"];
  if (!isRecord(failures.summary)) return ["failures.summary must be an object"];
  const errors: string[] = [];
  const ciSteps = failures.items.filter((item) => item.category === "ci-step").length;
  const lanes = failures.items.filter((item) => item.category === "lane").length;
  const validation = failures.items.filter((item) => item.category === "artifact-validation").length;
  if (failures.summary.total !== failures.items.length) errors.push("failures.summary.total must equal items length");
  if (failures.summary.ciSteps !== ciSteps) errors.push("failures.summary.ciSteps must equal ci-step items");
  if (failures.summary.lanes !== lanes) errors.push("failures.summary.lanes must equal lane items");
  if (failures.summary.artifactValidation !== validation) errors.push("failures.summary.artifactValidation must equal artifact-validation items");
  return errors;
}

function validateBundleManifestFile(
  path: string,
  required: boolean,
): HarnessArtifactValidationCheck {
  const manifest = readJsonIfPresent<HarnessBundleManifest>(path);
  if (!manifest) return validationCheck(
    "bundle-manifest",
    required ? "failed" : "passed",
    required ? "bundle-manifest.json is missing or invalid JSON" : "bundle-manifest.json is not present",
    path,
    required
      ? {
          expected: "valid bundle-manifest.json",
          actual: "missing or invalid JSON",
          hint: "Run bun run harness:ci to generate the final bundle manifest.",
          command: "bun run harness:ci",
        }
      : {},
  );

  const errors = validateBundleManifestShape(manifest);
  return validationCheck(
    "bundle-manifest",
    errors.length === 0 ? "passed" : "failed",
    errors.length === 0 ? "bundle manifest schema ok" : errors.join("; "),
    path,
    errors.length === 0
      ? {}
      : {
          expected: "bundle manifest schema, required files, and file hashes to be internally consistent",
          actual: errors.join("; "),
          hint: "Regenerate the bundle manifest with bun run harness:ci.",
          command: "bun run harness:ci",
        },
  );
}

function validateBundleManifestShape(manifest: HarnessBundleManifest): string[] {
  const errors: string[] = [];
  if (!isRecord(manifest)) return ["bundle manifest is not an object"];
  if (manifest.schemaVersion !== 1) errors.push("schemaVersion must be 1");
  if (typeof manifest.generatedAt !== "string" || !manifest.generatedAt) errors.push("generatedAt is required");
  if (typeof manifest.artifactRoot !== "string" || !manifest.artifactRoot) errors.push("artifactRoot is required");
  if (!Number.isInteger(manifest.fileCount) || manifest.fileCount < 0) errors.push("fileCount must be a non-negative integer");
  if (!Number.isInteger(manifest.totalBytes) || manifest.totalBytes < 0) errors.push("totalBytes must be a non-negative integer");
  if (!Array.isArray(manifest.requiredFiles)) {
    errors.push("requiredFiles must be an array");
  } else {
    const requiredPaths = new Set(manifest.requiredFiles.map((file) => file.path));
    for (const path of DEFAULT_HARNESS_BUNDLE_REQUIRED_FILES) {
      if (!requiredPaths.has(path)) errors.push(`requiredFiles must include ${path}`);
    }
    for (const [index, file] of manifest.requiredFiles.entries()) {
      if (!isRecord(file)) {
        errors.push(`requiredFiles[${index}] must be an object`);
        continue;
      }
      if (typeof file.path !== "string" || !file.path) errors.push(`requiredFiles[${index}].path is required`);
      if (file.status !== "present" && file.status !== "missing") errors.push(`requiredFiles[${index}].status is invalid`);
      if (file.status === "missing") errors.push(`required file missing: ${file.path}`);
    }
  }
  if (!Array.isArray(manifest.files)) {
    errors.push("files must be an array");
  } else {
    if (Number.isInteger(manifest.fileCount) && manifest.fileCount !== manifest.files.length) {
      errors.push("fileCount must equal files length");
    }
    const totalBytes = manifest.files.reduce((total, file) => total + (Number.isInteger(file.sizeBytes) ? file.sizeBytes : 0), 0);
    if (Number.isInteger(manifest.totalBytes) && manifest.totalBytes !== totalBytes) {
      errors.push("totalBytes must equal summed file sizes");
    }
    for (const [index, file] of manifest.files.entries()) {
      if (!isRecord(file)) {
        errors.push(`files[${index}] must be an object`);
        continue;
      }
      if (typeof file.path !== "string" || !file.path) errors.push(`files[${index}].path is required`);
      if (!Number.isInteger(file.sizeBytes) || file.sizeBytes < 0) errors.push(`files[${index}].sizeBytes is invalid`);
      if (typeof file.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(file.sha256)) {
        errors.push(`files[${index}].sha256 is invalid`);
      }
    }
  }
  return errors;
}

function validateHarnessArtifactContractValue(
  value: Record<string, unknown>,
  contract: HarnessArtifactContract,
): string[] {
  const errors: string[] = [];
  if (value.schemaVersion !== contract.schemaVersion) {
    errors.push(`schemaVersion must be ${contract.schemaVersion}`);
  }
  const expectedFields = [...contract.fields].sort((left, right) => left.localeCompare(right, "en"));
  const actualFields = Object.keys(value).sort((left, right) => left.localeCompare(right, "en"));
  const missing = expectedFields.filter((field) => !(field in value));
  const extra = actualFields.filter((field) => !expectedFields.includes(field));
  if (missing.length > 0) errors.push(`missing fields: ${missing.join(",")}`);
  if (extra.length > 0) errors.push(`unexpected fields: ${extra.join(",")}`);
  return errors;
}

