import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { buildOpenApiV1 } from "./v1";

type OpenApiOperation = {
  operationId?: string;
  tags?: string[];
  requestBody?: unknown;
  responses?: Record<string, unknown>;
};

type OpenApiDoc = {
  paths: Record<string, Record<string, OpenApiOperation>>;
};

const jsonOutputPath = resolve(import.meta.dir, "../../openapi/v1.json");
const endpointOutputPath = resolve(import.meta.dir, "generated/v1-endpoints.ts");

async function main() {
  const check = process.argv.includes("--check");
  const doc = buildOpenApiV1() as OpenApiDoc;
  const outputs = [
    {
      path: jsonOutputPath,
      content: `${JSON.stringify(doc, null, 2)}\n`,
    },
    {
      path: endpointOutputPath,
      content: renderEndpointMetadata(doc),
    },
  ];

  if (check) {
    for (const output of outputs) {
      const existing = await readFile(output.path, "utf8").catch(() => null);
      if (existing !== output.content) {
        console.error(`OpenAPI output is stale: ${output.path}`);
        console.error("Run: bun run protocol:openapi");
        process.exit(1);
      }
    }
    return;
  }

  for (const output of outputs) {
    await mkdir(dirname(output.path), { recursive: true });
    await writeFile(output.path, output.content);
  }
}

function renderEndpointMetadata(doc: OpenApiDoc): string {
  const endpoints = Object.entries(doc.paths).flatMap(([path, pathItem]) =>
    Object.entries(pathItem)
      .filter(([, operation]) => operation?.operationId)
      .map(([method, operation]) => ({
        operationId: operation.operationId ?? "",
        method: method.toUpperCase(),
        path,
        tags: operation.tags ?? [],
        hasRequestBody: operation.requestBody !== undefined,
        responseStatuses: Object.keys(operation.responses ?? {}).map(Number),
      })),
  );

  return [
    "/* This file is generated by packages/protocol/src/openapi/generate.ts. */",
    "/* Do not edit it manually. */",
    "",
    `export const OPENAPI_V1_ENDPOINTS = ${JSON.stringify(endpoints, null, 2)} as const;`,
    "",
    "export type OpenApiV1Endpoint = typeof OPENAPI_V1_ENDPOINTS[number];",
    "export type OpenApiV1OperationId = OpenApiV1Endpoint[\"operationId\"];",
    "export type OpenApiV1Method = OpenApiV1Endpoint[\"method\"];",
    "export type OpenApiV1Path = OpenApiV1Endpoint[\"path\"];",
    "export type OpenApiV1EndpointByOperationId<T extends OpenApiV1OperationId> =",
    "  Extract<OpenApiV1Endpoint, { operationId: T }>;",
    "",
  ].join("\n");
}

await main();
